<?php

/**
 * @file
 * OpenID Connect client implementation.
 */

/**
 * Implements hook_block_info().
 */
function openid_connect_block_info() {
  return array(
    'google_login' => array(
      'info' => t('Log in with Google'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function openid_connect_block_view($delta = '') {
  if ($delta == 'google_login') {
    return array(
      'subject' => t('Testing OpenID Connect'),
      'content' => drupal_get_form('openid_connect_login_form'),
    );
  }
}

/**
 * Form builder: Log in with Google form.
 */
function openid_connect_login_form($form, &$form_state) {
  $form['google_login'] = array(
    '#type' => 'submit',
    '#value' => t('Log in with Google'),
  );
  return $form;
}

/**
 * Form submit handler: Log in with Google form.
 */
function openid_connect_login_form_submit(&$form, &$form_state) {
  // Create a state token to prevent request forgery. Store it in the session
  // for later validation.
  $_SESSION['openid_connect_state'] = md5(rand());
}
